name: Monkeytype Readme Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs at exactly 10:34 AM IST
  workflow_dispatch: # Allows manual triggering

# Explicitly grant write access to the repository contents
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Monkeytype Readme
        uses: monkeytype-hub/monkeytype-readme@master
        with:
          username: aditya76-mt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
