name: Monkeytype Readme Update

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Monkeytype Readme
        uses: monkeytype-hub/monkeytype-readme@master
        with:
          username: aditya76-mt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
